"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = require("styled-components");
var Button = styled_components_1.default.button(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  letter-spacing: 0.02857em;\n  text-transform: uppercase;\n  position: relative;\n  user-select: none;\n  vertical-align: middle;\n  text-decoration: none;\n  color: rgb(62, 166, 255);\n  border-radius: 3px;\n  border: 1px solid rgb(62, 166, 255);\n  padding: 10px 15px;\n  background-color: transparent;\n  font-size: 0.875rem;\n  font-weight: 500;\n  line-height: 1.75;\n  min-width: 64px;\n  box-sizing: border-box;\n  transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms,\n    box-shadow 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms,\n    border 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms;\n  font-family: Roboto, Helvetica, Arial, sans-serif;\n\n  .outer {\n    display: flex;\n    align-items: center;\n    white-space: nowrap;\n  }\n\n  .inner {\n    display: inherit;\n    margin-left: -4px;\n    margin-right: 8px;\n    font-size: 24px;\n    white-space: nowrap;\n  }\n"], ["\n  letter-spacing: 0.02857em;\n  text-transform: uppercase;\n  position: relative;\n  user-select: none;\n  vertical-align: middle;\n  text-decoration: none;\n  color: rgb(62, 166, 255);\n  border-radius: 3px;\n  border: 1px solid rgb(62, 166, 255);\n  padding: 10px 15px;\n  background-color: transparent;\n  font-size: 0.875rem;\n  font-weight: 500;\n  line-height: 1.75;\n  min-width: 64px;\n  box-sizing: border-box;\n  transition: background-color 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms,\n    box-shadow 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms,\n    border 250ms cubic-bezier(0.4, 0, 0.2, 1) 0ms;\n  font-family: Roboto, Helvetica, Arial, sans-serif;\n\n  .outer {\n    display: flex;\n    align-items: center;\n    white-space: nowrap;\n  }\n\n  .inner {\n    display: inherit;\n    margin-left: -4px;\n    margin-right: 8px;\n    font-size: 24px;\n    white-space: nowrap;\n  }\n"])));
exports.default = Button;
var templateObject_1;
