"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
// @ts-nocheck
var styled_components_1 = require("styled-components");
var Wrapper = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  margin: 2rem 0;\n\n  .avatar-channel {\n    display: flex;\n    align-items: center;\n  }\n\n  .channel-info-meta {\n    line-height: 1.5;\n  }\n\n  .subscribe-channel {\n    display: flex;\n    align-items: center;\n  }\n\n  .description {\n    width: 90%;\n  }\n\n  img {\n    width: 120px;\n    height: 120px;\n    border-radius: 60px;\n    object-fit: cover;\n    margin-right: 1.2rem;\n  }\n\n  p span:first {\n    padding-right: 0.6rem;\n  }\n\n  @media screen and (max-width: 580px) {\n    font-size: 0.9rem;\n\n    button {\n      font-size: 0.9rem;\n    }\n\n    img {\n      width: 100px;\n      height: 100px;\n      border-radius: 50px;\n    }\n  }\n\n  @media screen and (max-width: 510px) {\n    p.description {\n      display: none;\n    }\n  }\n\n  @media screen and (max-width: 450px) {\n    img {\n      width: 50px;\n      height: 50px;\n      border-radius: 25px;\n    }\n  }\n\n  @media screen and (max-width: 420px) {\n    .to-hide {\n      display: none;\n    }\n  }\n"], ["\n  display: flex;\n  align-items: center;\n  justify-content: space-between;\n  margin: 2rem 0;\n\n  .avatar-channel {\n    display: flex;\n    align-items: center;\n  }\n\n  .channel-info-meta {\n    line-height: 1.5;\n  }\n\n  .subscribe-channel {\n    display: flex;\n    align-items: center;\n  }\n\n  .description {\n    width: 90%;\n  }\n\n  img {\n    width: 120px;\n    height: 120px;\n    border-radius: 60px;\n    object-fit: cover;\n    margin-right: 1.2rem;\n  }\n\n  p span:first {\n    padding-right: 0.6rem;\n  }\n\n  @media screen and (max-width: 580px) {\n    font-size: 0.9rem;\n\n    button {\n      font-size: 0.9rem;\n    }\n\n    img {\n      width: 100px;\n      height: 100px;\n      border-radius: 50px;\n    }\n  }\n\n  @media screen and (max-width: 510px) {\n    p.description {\n      display: none;\n    }\n  }\n\n  @media screen and (max-width: 450px) {\n    img {\n      width: 50px;\n      height: 50px;\n      border-radius: 25px;\n    }\n  }\n\n  @media screen and (max-width: 420px) {\n    .to-hide {\n      display: none;\n    }\n  }\n"])));
exports.default = Wrapper;
var templateObject_1;
