"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = require("styled-components");
var Wrapper = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  min-height: 100vh;\n\n  .channel-avatar-info {\n    display: flex;\n    align-items: center;\n    width: 80%;\n    margin: 1rem auto;\n  }\n\n  .avatar {\n    margin-right: 1rem;\n    width: 120px;\n    height: 120px;\n    border-radius: 60px;\n  }\n\n  .videos {\n    display: grid;\n    grid-template-columns: repeat(3, 1fr);\n    grid-gap: 2rem;\n    margin: 0 auto;\n    margin-top: 2rem;\n    width: 80%;\n  }\n\n  @media screen and (max-width: 860px) {\n    .videos {\n      width: 90%;\n    }\n  }\n\n  @media screen and (max-width: 830px) {\n    .videos {\n      grid-template-columns: repeat(2, 1fr);\n    }\n  }\n\n  @media screen and (max-width: 540px) {\n    .videos {\n      grid-template-columns: 1fr;\n    }\n  }\n\n  @media screen and (max-width: 500px) {\n    .channel-avatar-info {\n      width: 100%;\n      padding: 1rem;\n    }\n\n    .avatar {\n      width: 100px;\n      height: 100px;\n      border-radius: 50px;\n    }\n  }\n\n  @media screen and (max-width: 420px) {\n    .avatar {\n      width: 70px;\n      height: 70px;\n      border-radius: 35px;\n      position: relative;\n      top: -3px;\n    }\n\n    .channel-info {\n      width: 80%;\n    }\n  }\n\n  @media screen and (max-width: 390px) {\n    .avatar {\n      width: 50px;\n      height: 50px;\n      border-radius: 25px;\n      position: relative;\n      top: -20px;\n    }\n\n    .channel-info {\n      width: 80%;\n    }\n  }\n"], ["\n  min-height: 100vh;\n\n  .channel-avatar-info {\n    display: flex;\n    align-items: center;\n    width: 80%;\n    margin: 1rem auto;\n  }\n\n  .avatar {\n    margin-right: 1rem;\n    width: 120px;\n    height: 120px;\n    border-radius: 60px;\n  }\n\n  .videos {\n    display: grid;\n    grid-template-columns: repeat(3, 1fr);\n    grid-gap: 2rem;\n    margin: 0 auto;\n    margin-top: 2rem;\n    width: 80%;\n  }\n\n  @media screen and (max-width: 860px) {\n    .videos {\n      width: 90%;\n    }\n  }\n\n  @media screen and (max-width: 830px) {\n    .videos {\n      grid-template-columns: repeat(2, 1fr);\n    }\n  }\n\n  @media screen and (max-width: 540px) {\n    .videos {\n      grid-template-columns: 1fr;\n    }\n  }\n\n  @media screen and (max-width: 500px) {\n    .channel-avatar-info {\n      width: 100%;\n      padding: 1rem;\n    }\n\n    .avatar {\n      width: 100px;\n      height: 100px;\n      border-radius: 50px;\n    }\n  }\n\n  @media screen and (max-width: 420px) {\n    .avatar {\n      width: 70px;\n      height: 70px;\n      border-radius: 35px;\n      position: relative;\n      top: -3px;\n    }\n\n    .channel-info {\n      width: 80%;\n    }\n  }\n\n  @media screen and (max-width: 390px) {\n    .avatar {\n      width: 50px;\n      height: 50px;\n      border-radius: 25px;\n      position: relative;\n      top: -20px;\n    }\n\n    .channel-info {\n      width: 80%;\n    }\n  }\n"])));
exports.default = Wrapper;
var templateObject_1;
