"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = require("styled-components");
var Wrapper = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  margin: 1rem 0;\n\n  h3 {\n    margin-bottom: 0.8rem;\n  }\n\n  .add-comment {\n    display: flex;\n    align-items: center;\n    margin-top: 1.5rem;\n    margin-bottom: 2rem;\n  }\n\n  .add-comment textarea {\n    background: inherit;\n    border: none;\n    border-bottom: 1px solid ", ";\n    color: ", ";\n    width: 100%;\n    height: 100%;\n    padding-bottom: 10px;\n  }\n\n  .add-comment img {\n    width: 40px;\n    height: 40px;\n    border-radius: 20px;\n    object-fit: cover;\n    margin-right: 1rem;\n  }\n\n  .comment {\n    display: flex;\n    margin-bottom: 2rem;\n    font-size: 0.9rem;\n  }\n\n  .comment img {\n    width: 40px;\n    object-fit: cover;\n    height: 40px;\n    border-radius: 20px;\n    position: relative;\n    top: 2px;\n    margin-right: 1rem;\n  }\n\n  .user-channel {\n    font-weight: bold;\n    color: white;\n  }\n"], ["\n  margin: 1rem 0;\n\n  h3 {\n    margin-bottom: 0.8rem;\n  }\n\n  .add-comment {\n    display: flex;\n    align-items: center;\n    margin-top: 1.5rem;\n    margin-bottom: 2rem;\n  }\n\n  .add-comment textarea {\n    background: inherit;\n    border: none;\n    border-bottom: 1px solid ", ";\n    color: ", ";\n    width: 100%;\n    height: 100%;\n    padding-bottom: 10px;\n  }\n\n  .add-comment img {\n    width: 40px;\n    height: 40px;\n    border-radius: 20px;\n    object-fit: cover;\n    margin-right: 1rem;\n  }\n\n  .comment {\n    display: flex;\n    margin-bottom: 2rem;\n    font-size: 0.9rem;\n  }\n\n  .comment img {\n    width: 40px;\n    object-fit: cover;\n    height: 40px;\n    border-radius: 20px;\n    position: relative;\n    top: 2px;\n    margin-right: 1rem;\n  }\n\n  .user-channel {\n    font-weight: bold;\n    color: white;\n  }\n"])), function (props) { return props.theme.darkGrey; }, function (props) { return props.theme.primaryColor; });
exports.default = Wrapper;
var templateObject_1;
