"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = require("styled-components");
var Wrapper = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  position: fixed;\n  top: 0;\n  left: 0;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  width: 100%;\n  background: ", ";\n  z-index: 99;\n  padding: 0.7rem 1.5rem;\n\n  input {\n    width: 500px;\n  }\n\n  .hamburger-icon {\n    display: none;\n  }\n\n  .logo span {\n    position: relative;\n    top: 1px;\n  }\n\n  ul {\n    list-style: none;\n    display: flex;\n    position: relative;\n  }\n\n  li svg {\n    margin-right: 1.7rem;\n    position: relative;\n  }\n\n  ul {\n    display: flex;\n    align-items: center;\n  }\n\n  img {\n    position: relative;\n    top: 3px;\n  }\n\n  @media screen and (max-width: 1093px) {\n    .hamburger-icon {\n      display: block;\n    }\n  }\n\n  @media screen and (max-width: 1000px) {\n    input {\n      width: 400px;\n    }\n  }\n\n  @media screen and (max-width: 850px) {\n    input {\n      width: 280px;\n    }\n  }\n\n  @media screen and (max-width: 500px) {\n    .hamburger-icon {\n      display: none;\n    }\n\n    li svg {\n      width: 30px;\n      height: 30px;\n      margin-right: 1.7rem;\n      position: relative;\n    }\n  }\n\n  @media screen and (max-width: 400px) {\n    li svg {\n      display: none;\n    }\n  }\n"], ["\n  position: fixed;\n  top: 0;\n  left: 0;\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  width: 100%;\n  background: ", ";\n  z-index: 99;\n  padding: 0.7rem 1.5rem;\n\n  input {\n    width: 500px;\n  }\n\n  .hamburger-icon {\n    display: none;\n  }\n\n  .logo span {\n    position: relative;\n    top: 1px;\n  }\n\n  ul {\n    list-style: none;\n    display: flex;\n    position: relative;\n  }\n\n  li svg {\n    margin-right: 1.7rem;\n    position: relative;\n  }\n\n  ul {\n    display: flex;\n    align-items: center;\n  }\n\n  img {\n    position: relative;\n    top: 3px;\n  }\n\n  @media screen and (max-width: 1093px) {\n    .hamburger-icon {\n      display: block;\n    }\n  }\n\n  @media screen and (max-width: 1000px) {\n    input {\n      width: 400px;\n    }\n  }\n\n  @media screen and (max-width: 850px) {\n    input {\n      width: 280px;\n    }\n  }\n\n  @media screen and (max-width: 500px) {\n    .hamburger-icon {\n      display: none;\n    }\n\n    li svg {\n      width: 30px;\n      height: 30px;\n      margin-right: 1.7rem;\n      position: relative;\n    }\n  }\n\n  @media screen and (max-width: 400px) {\n    li svg {\n      display: none;\n    }\n  }\n"])), function (props) { return props.theme.grey; });
exports.default = Wrapper;
var templateObject_1;
