"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChannelInfoSkeleton = exports.TrendingCardSkeleton = exports.VideoCardSkeleton = exports.SkeletonLine = void 0;
// @ts-nocheck
var styled_components_1 = require("styled-components");
var pulse = styled_components_1.keyframes(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n\t0% {\n\t\tbackground-position: 0% 0%;\n\t}\n\n\t100% {\n\t\tbackground-position: -135% 0%;\n\t}\n"], ["\n\t0% {\n\t\tbackground-position: 0% 0%;\n\t}\n\n\t100% {\n\t\tbackground-position: -135% 0%;\n\t}\n"])));
var SkeletonPulse = styled_components_1.default.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  display: block;\n  height: 100%;\n  width: 100%;\n  background: linear-gradient(-90deg, #121212 0%, #161616 50%, #121212 100%);\n  background-size: 400% 400%;\n  animation: ", " 1s alternate;\n  animation-iteration-count: infinite;\n"], ["\n  display: block;\n  height: 100%;\n  width: 100%;\n  background: linear-gradient(-90deg, #121212 0%, #161616 50%, #121212 100%);\n  background-size: 400% 400%;\n  animation: ", " 1s alternate;\n  animation-iteration-count: infinite;\n"])), pulse);
exports.SkeletonLine = styled_components_1.default(SkeletonPulse)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  margin-bottom: ", ";\n  margin-top: ", ";\n  margin-left: ", ";\n  margin-right: ", ";\n  width: ", ";\n  height: ", ";\n  border-radius: 4px;\n\n  &::before {\n    content: \"\\00a0\";\n  }\n"], ["\n  margin-bottom: ", ";\n  margin-top: ", ";\n  margin-left: ", ";\n  margin-right: ", ";\n  width: ", ";\n  height: ", ";\n  border-radius: 4px;\n\n  &::before {\n    content: \"\\\\00a0\";\n  }\n"])), function (props) { return (props.mb ? props.mb : ""); }, function (props) { return (props.mt ? props.mt : ""); }, function (props) { return (props.ml ? props.ml : ""); }, function (props) { return (props.mr ? props.mr : ""); }, function (props) { return props.width; }, function (props) { return props.height; });
exports.VideoCardSkeleton = styled_components_1.default(exports.SkeletonLine)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  width: 100%;\n  height: 180px;\n\n  @media screen and (max-width: 600px) {\n    height: 250px;\n  }\n\n  @media screen and (max-width: 420px) {\n    height: 200px;\n  }\n"], ["\n  width: 100%;\n  height: 180px;\n\n  @media screen and (max-width: 600px) {\n    height: 250px;\n  }\n\n  @media screen and (max-width: 420px) {\n    height: 200px;\n  }\n"])));
exports.TrendingCardSkeleton = styled_components_1.default(exports.SkeletonLine)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n  width: 250px;\n  height: 140px;\n\n  @media screen and (max-width: 645px) {\n    width: 100%;\n    height: 300px;\n  }\n\n  @media screen and (max-width: 530px) {\n    width: 100%;\n    height: 250px;\n  }\n\n  @media screen and (max-width: 420px) {\n    width: 100%;\n    height: 200px;\n  }\n"], ["\n  width: 250px;\n  height: 140px;\n\n  @media screen and (max-width: 645px) {\n    width: 100%;\n    height: 300px;\n  }\n\n  @media screen and (max-width: 530px) {\n    width: 100%;\n    height: 250px;\n  }\n\n  @media screen and (max-width: 420px) {\n    width: 100%;\n    height: 200px;\n  }\n"])));
exports.ChannelInfoSkeleton = styled_components_1.default(exports.SkeletonLine)(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n\twidth: 134px;\n\theight: 134px;\n\tborder-radius: 67px;\n\tmargin-right: 1.2rem;\n\n\t@media screen and (max-width: 580px) {\n\t\twidth: 100px;\n\t\theight: 100px;\n\t}\n\n\t@media screen and (max-width: 400px) {\n\t\twidth: 50px;\n\t\theight: 50px;\n\t\tposition: relative;\n\t\ttop: -16px;\n"], ["\n\twidth: 134px;\n\theight: 134px;\n\tborder-radius: 67px;\n\tmargin-right: 1.2rem;\n\n\t@media screen and (max-width: 580px) {\n\t\twidth: 100px;\n\t\theight: 100px;\n\t}\n\n\t@media screen and (max-width: 400px) {\n\t\twidth: 50px;\n\t\theight: 50px;\n\t\tposition: relative;\n\t\ttop: -16px;\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6;
