"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = require("styled-components");
var Wrapper = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  margin: 1.4rem 0;\n  margin-top: 1rem;\n  display: flex;\n\n  .thumb {\n    width: 250px;\n    height: 140px;\n    box-shadow: 0px 1px 5px 0px rgba(0, 0, 0, 0.2);\n    border-radius: 4px;\n  }\n\n  .video-info-container {\n    margin-left: 1.2rem;\n  }\n\n  p {\n    font-size: 0.9rem;\n  }\n\n  p:last-child {\n    margin-top: 0.2rem;\n  }\n\n  p span {\n    padding-right: 0.3rem;\n  }\n\n  @media screen and (max-width: 750px) {\n    margin: 1.2rem 0;\n\n    .video-info-container {\n      margin-left: 1.5rem;\n    }\n  }\n\n  @media screen and (max-width: 645px) {\n    flex-direction: column;\n\n    .video-info-container {\n      padding-bottom: 1rem;\n    }\n\n    .thumb {\n      width: 100%;\n      height: 300px;\n    }\n\n    .video-info-container {\n      margin-left: 0;\n      margin-top: 1rem;\n    }\n  }\n\n  @media screen and (max-width: 530px) {\n    .thumb {\n      width: 100%;\n      height: 250px;\n    }\n  }\n\n  @media screen and (max-width: 420px) {\n    .thumb {\n      width: 100%;\n      height: 200px;\n    }\n  }\n"], ["\n  margin: 1.4rem 0;\n  margin-top: 1rem;\n  display: flex;\n\n  .thumb {\n    width: 250px;\n    height: 140px;\n    box-shadow: 0px 1px 5px 0px rgba(0, 0, 0, 0.2);\n    border-radius: 4px;\n  }\n\n  .video-info-container {\n    margin-left: 1.2rem;\n  }\n\n  p {\n    font-size: 0.9rem;\n  }\n\n  p:last-child {\n    margin-top: 0.2rem;\n  }\n\n  p span {\n    padding-right: 0.3rem;\n  }\n\n  @media screen and (max-width: 750px) {\n    margin: 1.2rem 0;\n\n    .video-info-container {\n      margin-left: 1.5rem;\n    }\n  }\n\n  @media screen and (max-width: 645px) {\n    flex-direction: column;\n\n    .video-info-container {\n      padding-bottom: 1rem;\n    }\n\n    .thumb {\n      width: 100%;\n      height: 300px;\n    }\n\n    .video-info-container {\n      margin-left: 0;\n      margin-top: 1rem;\n    }\n  }\n\n  @media screen and (max-width: 530px) {\n    .thumb {\n      width: 100%;\n      height: 250px;\n    }\n  }\n\n  @media screen and (max-width: 420px) {\n    .thumb {\n      width: 100%;\n      height: 200px;\n    }\n  }\n"])));
exports.default = Wrapper;
var templateObject_1;
