"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = require("styled-components");
var Wrapper = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  .thumb {\n    width: 100%;\n    height: 180px;\n    object-fit: cover;\n    box-shadow: 0px 1px 5px 0px rgba(0, 0, 0, 0.2);\n    border-radius: 4px;\n  }\n\n  .truncate {\n    overflow: hidden;\n    text-overflow: ellipsis;\n    white-space: nowrap;\n  }\n\n  .leading-4 {\n    line-height: 1;\n  }\n\n  .video-info-container {\n    display: flex;\n    margin-top: 0.3rem;\n  }\n\n  .channel-avatar img {\n    position: relative;\n    top: 5px;\n  }\n\n  .video-info {\n    flex: 1 1 0;\n  }\n\n  .video-info span {\n    font-size: 0.9rem;\n    padding-right: 0.1rem;\n  }\n\n  @media screen and (max-width: 600px) {\n    .thumb {\n      height: 250px;\n    }\n  }\n\n  @media screen and (max-width: 420px) {\n    .thumb {\n      height: 200px;\n    }\n  }\n"], ["\n  .thumb {\n    width: 100%;\n    height: 180px;\n    object-fit: cover;\n    box-shadow: 0px 1px 5px 0px rgba(0, 0, 0, 0.2);\n    border-radius: 4px;\n  }\n\n  .truncate {\n    overflow: hidden;\n    text-overflow: ellipsis;\n    white-space: nowrap;\n  }\n\n  .leading-4 {\n    line-height: 1;\n  }\n\n  .video-info-container {\n    display: flex;\n    margin-top: 0.3rem;\n  }\n\n  .channel-avatar img {\n    position: relative;\n    top: 5px;\n  }\n\n  .video-info {\n    flex: 1 1 0;\n  }\n\n  .video-info span {\n    font-size: 0.9rem;\n    padding-right: 0.1rem;\n  }\n\n  @media screen and (max-width: 600px) {\n    .thumb {\n      height: 250px;\n    }\n  }\n\n  @media screen and (max-width: 420px) {\n    .thumb {\n      height: 200px;\n    }\n  }\n"])));
exports.default = Wrapper;
var templateObject_1;
