"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
// @ts-nocheck
var styled_components_1 = require("styled-components");
var Wrapper = styled_components_1.default.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  display: grid;\n  grid-template-columns: 70% 1fr;\n  grid-gap: 2rem;\n  padding: 1.75em;\n  padding-bottom: 7rem;\n\n  .video-container .video-info {\n    margin-top: 1rem;\n    margin-bottom: 1rem;\n  }\n\n  .video-info span {\n    color: ", ";\n  }\n\n  .channel-info-flex {\n    display: flex;\n    justify-content: space-between;\n    align-items: center;\n  }\n\n  .channel-info-meta {\n    line-height: 1.2;\n  }\n\n  .video-info-stats {\n    display: flex;\n    align-items: center;\n  }\n\n  .video-info-stats div {\n    margin-left: 6rem;\n    position: relative;\n    top: -2px;\n  }\n\n  .channel-info-flex button {\n    font-size: 0.9rem;\n  }\n\n  .channel-info-description {\n    padding-top: 1rem;\n    border-bottom: 1px solid ", ";\n    border-top: 1px solid ", ";\n  }\n\n  .channel-info-description p {\n    font-size: 0.9rem;\n    padding: 1rem 0;\n  }\n\n  .up-next {\n    margin-bottom: 1em;\n  }\n\n  // .related-videos img {\n  //   height: 140px;\n  // }\n\n  .related-videos div {\n    margin-bottom: 1rem;\n  }\n\n  related-videos h3 {\n    margin-bottom: 1rem;\n  }\n\n  svg {\n    fill: ", ";\n  }\n\n  ", "\n\n  ", "\n\n\t@media screen and (max-width: 930px) {\n    grid-template-columns: 90%;\n    .related-videos {\n      display: none;\n    }\n  }\n\n  @media screen and (max-width: 930px) {\n    grid-template-columns: 1fr;\n  }\n\n  @media screen and (max-width: 425px) {\n    .video-info-stats div {\n      margin-left: 1rem;\n    }\n  }\n"], ["\n  display: grid;\n  grid-template-columns: 70% 1fr;\n  grid-gap: 2rem;\n  padding: 1.75em;\n  padding-bottom: 7rem;\n\n  .video-container .video-info {\n    margin-top: 1rem;\n    margin-bottom: 1rem;\n  }\n\n  .video-info span {\n    color: ", ";\n  }\n\n  .channel-info-flex {\n    display: flex;\n    justify-content: space-between;\n    align-items: center;\n  }\n\n  .channel-info-meta {\n    line-height: 1.2;\n  }\n\n  .video-info-stats {\n    display: flex;\n    align-items: center;\n  }\n\n  .video-info-stats div {\n    margin-left: 6rem;\n    position: relative;\n    top: -2px;\n  }\n\n  .channel-info-flex button {\n    font-size: 0.9rem;\n  }\n\n  .channel-info-description {\n    padding-top: 1rem;\n    border-bottom: 1px solid ", ";\n    border-top: 1px solid ", ";\n  }\n\n  .channel-info-description p {\n    font-size: 0.9rem;\n    padding: 1rem 0;\n  }\n\n  .up-next {\n    margin-bottom: 1em;\n  }\n\n  // .related-videos img {\n  //   height: 140px;\n  // }\n\n  .related-videos div {\n    margin-bottom: 1rem;\n  }\n\n  related-videos h3 {\n    margin-bottom: 1rem;\n  }\n\n  svg {\n    fill: ", ";\n  }\n\n  ",
    "\n\n  ",
    "\n\n\t@media screen and (max-width: 930px) {\n    grid-template-columns: 90%;\n    .related-videos {\n      display: none;\n    }\n  }\n\n  @media screen and (max-width: 930px) {\n    grid-template-columns: 1fr;\n  }\n\n  @media screen and (max-width: 425px) {\n    .video-info-stats div {\n      margin-left: 1rem;\n    }\n  }\n"])), function (props) { return props.theme.secondaryColor; }, function (props) { return props.theme.darkGrey; }, function (props) { return props.theme.darkGrey; }, function (props) { return props.theme.darkGrey; }, function (props) {
    return props.filledLike && styled_components_1.css(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n      .like svg {\n        fill: ", ";\n      }\n    "], ["\n      .like svg {\n        fill: ", ";\n      }\n    "])), function (props) { return props.theme.blue; });
}, function (props) {
    return props.filledDislike && styled_components_1.css(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n      .dislike svg {\n        fill: ", ";\n      }\n    "], ["\n      .dislike svg {\n        fill: ", ";\n      }\n    "])), function (props) { return props.theme.blue; });
});
exports.default = Wrapper;
var templateObject_1, templateObject_2, templateObject_3;
