"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
var styled_components_1 = require("styled-components");
var Wrapper = styled_components_1.default.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  display: grid;\n  grid-template-columns: 70% 1fr;\n  grid-gap: 2rem;\n  padding: 1.75rem;\n\n  .avatar-card {\n    display: flex;\n    align-items: center;\n    margin-top: 2rem;\n  }\n\n  .avatar {\n    height: 100px;\n    width: 100px;\n    border-radius: 50px;\n  }\n\n  .video {\n    height: 340px;\n  }\n\n  .related-videos img {\n    height: 140px;\n  }\n\n  .related-videos div {\n    margin-bottom: 1rem;\n  }\n\n  @media screen and (max-width: 930px) {\n    grid-template-columns: 1fr;\n    .related-videos {\n      display: none;\n    }\n  }\n\n  @media screen and (max-width: 500px) {\n    .video {\n      height: 250px;\n    }\n  }\n\n  @media screen and (max-width: 400px) {\n    .avatar-card {\n      margin-top: 3rem;\n    }\n\n    .avatar {\n      height: 70px;\n      width: 70px;\n      border-radius: 35px;\n      position: relative;\n      top: -5px;\n    }\n  }\n"], ["\n  display: grid;\n  grid-template-columns: 70% 1fr;\n  grid-gap: 2rem;\n  padding: 1.75rem;\n\n  .avatar-card {\n    display: flex;\n    align-items: center;\n    margin-top: 2rem;\n  }\n\n  .avatar {\n    height: 100px;\n    width: 100px;\n    border-radius: 50px;\n  }\n\n  .video {\n    height: 340px;\n  }\n\n  .related-videos img {\n    height: 140px;\n  }\n\n  .related-videos div {\n    margin-bottom: 1rem;\n  }\n\n  @media screen and (max-width: 930px) {\n    grid-template-columns: 1fr;\n    .related-videos {\n      display: none;\n    }\n  }\n\n  @media screen and (max-width: 500px) {\n    .video {\n      height: 250px;\n    }\n  }\n\n  @media screen and (max-width: 400px) {\n    .avatar-card {\n      margin-top: 3rem;\n    }\n\n    .avatar {\n      height: 70px;\n      width: 70px;\n      border-radius: 35px;\n      position: relative;\n      top: -5px;\n    }\n  }\n"])));
exports.default = Wrapper;
var templateObject_1;
